### ISSUE TITLE
Unexpected keyword argument 'bot'

### ISSUE THREAD

**Issue by ptomkiel-oktawave** [skoczen/will#313]
Hey,

Thanks for your work in making Will better every day. After updating to 2.0 we have an error:
`__init__() got an unexpected keyword argument 'bot'` from "/home/pawel/sources/python-bot-will/will/main.py", line 1047, in bootstrap_plugins

in loading one of our own plugins extending WillBot.

Can you give me a clue, what can be wrong?

**Comment by skoczen** [comment]
Hey @ptomkiel-oktawave ,

My first guess is that you're passing in `bot` into the constructor method of one of your subclasses - can you paste the code for the plugin that's causing you trouble, or the full traceback?

Thanks much!
-Steven

**Comment by skoczen** [comment]
My second thought is stray *.pyc files.  Give `find . -iname "*.pyc" -delete` a shot and re-run?

**Comment by ptomkiel-oktawave** [comment]
Actually it's the opposite, main.py is passing bot into my plugins with:
`if plugin_info["class"] in plugin_instances:
                                                    instance = plugin_instances[plugin_info["class"]]
                                                else:
                                                    instance = plugin_info["class"](bot=self)
                                                    plugin_instances[plugin_info["class"]] = instance`

I added such parameter to my `__init__` and now everything 's working fine :)

**Comment by skoczen** [comment]
This mention of `__init__` suggests to me that you might be overridding `__init__` without calling `super()` ?    Perhaps?

**Comment by ptomkiel-oktawave** [comment]
Yup, that was it. Something that worked well in 1.0 stopped working in 2.0 :)
